import { useState, useEffect, useCallback } from 'react';
import { alert, patient, user, caseSheetEntry } from '../types';
import { PatientService } from '../services';
import { useDataRefresh } from './useDataRefresh';
import { getApiUrl } from '../config/apiConfig';

interface UsePatientAlertsProps {
  patient: patient;
  currentUser: user;
  alerts: alert[];
  setAlerts: React.Dispatch<React.SetStateAction<alert[]>>;
  addCaseSheetEntry: (entry: caseSheetEntry) => void;
  setCaseEntries: React.Dispatch<React.SetStateAction<caseSheetEntry[]>>;
}

export const usePatientAlerts = ({
  patient,
  currentUser,
  alerts,
  setAlerts,
  addCaseSheetEntry,
  setCaseEntries
}: UsePatientAlertsProps) => {
  // Initialize data refresh hook for single source of truth
  const { refreshAlerts, refreshCaseEntries } = useDataRefresh(patient.id);
  const [autoHideTimers, setAutoHideTimers] = useState<{[key: string]: NodeJS.Timeout}>({});

  // Acknowledge alert handler using atomic operation
  const handleAcknowledgeAlert = useCallback(async (alertId: string) => {
    try {
      const alertToAck = alerts.find(a => a.id === alertId);
      if (!alertToAck) return;


      // Use atomic endpoint - updates alert and creates case entry in single transaction
      const response = await fetch(getApiUrl(`/atomic/patients/${patient.id}/alerts/${alertId}/acknowledge`), {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          alert_id: alertId,
          acknowledged_by: currentUser.staffId
        })
      });

      if (!response.ok) {
        throw new Error(`Failed to acknowledge alert: ${response.statusText}`);
      }

      const result = await response.json();

      if (result.success) {
        // Refetch fresh data from backend (single source of truth)
        try {
          const freshAlerts = await refreshAlerts();
          setAlerts(freshAlerts);

          const freshCaseEntries = await refreshCaseEntries();
          setCaseEntries(freshCaseEntries);

        } catch (refreshError) {
          // Failed to refresh data after alert acknowledgment - handle silently
        }
      } else {
        throw new Error('Atomic operation failed');
      }

      // Set auto-hide timer for acknowledged alerts
      const timer = setTimeout(async () => {
        // Refetch fresh data from backend (single source of truth)
        try {
          const freshAlerts = await refreshAlerts();
          setAlerts(freshAlerts);
        } catch (refreshError) {
          // Failed to refresh alerts after auto-hide - handle silently
        }
        setAutoHideTimers(prev => {
          const newTimers = { ...prev };
          delete newTimers[alertId];
          return newTimers;
        });
      }, 30000); // Hide after 30 seconds

      setAutoHideTimers(prev => ({ ...prev, [alertId]: timer }));

    } catch (error) {
      // Error acknowledging alert - handle silently
      alert(`❌ Failed to acknowledge alert: ${(error as Error).message}`);
    }
  }, [alerts, setAlerts, currentUser, setCaseEntries, patient.id, refreshAlerts, refreshCaseEntries]);

  // REMOVED: Frontend clinical alert generation
  // All clinical alerts now come from backend only
  // Backend handles all medical logic and clinical decision making

  // Clean up timers on unmount
  useEffect(() => {
    return () => {
      Object.values(autoHideTimers).forEach(timer => clearTimeout(timer));
    };
  }, [autoHideTimers]);

  // REMOVED: Frontend alert generation interval
  // All clinical alerts now generated by backend only

  return {
    handleAcknowledgeAlert
  };
};