import React, { useEffect, useRef } from 'react';
import { patient } from '../../types';
import { useECGViewer } from '../../hooks/useECGViewer';
import { ECGViewerHeader } from './ECGViewerHeader';
import { ECGDisplayGrid } from './ECGDisplayGrid';
import {
  BUFFER_MAX_SAMPLES,
} from '../../config/ecgConfig';

// Props for the ECG viewer container component
interface ECGViewerContainerProps {
  patient: patient;
  onClose: () => void;
}

// Main component to manage ECG/EEG viewer state and rendering
export const ECGViewerContainer: React.FC<ECGViewerContainerProps> = ({ patient, onClose }) => {
  const {
    isECGMode,
    speed,
    gain,
    isPaused,
    selectedLead,
    layout,
    leads,
    canvasRefs,
    dataBufferRef,
    setIsECGMode,
    setSpeed,
    setGain,
    setIsPaused,
    setSelectedLead,
    setLayout,
    getLatestValue
  } = useECGViewer({ patient });

  const isInitialized = useRef<boolean>(false);

  // Initialize buffers
  useEffect(() => {
    if (!isInitialized.current) {
      leads.forEach((_, index) => {
        if (!dataBufferRef.current[index]) {
          dataBufferRef.current[index] = [];
        }
      });
      isInitialized.current = true;
    }

    // ✅ DISABLED: Calibration pulse now generated by ESP32 watch
    // Frontend-generated calibration removed - watch sends real calibration via waveform stream
    // if (isECGMode && !hasPulseAdded.current.every(Boolean)) {
    //   const headSamples = new Array(CALIBRATION_HEAD_SAMPLES).fill(CALIBRATION_BASELINE_ADC);
    //   const pulseSamples = new Array(CALIBRATION_PULSE_SAMPLES).fill(CALIBRATION_PULSE_ADC);
    //   const tailSamples = new Array(CALIBRATION_TAIL_SAMPLES).fill(CALIBRATION_BASELINE_ADC);
    //   console.log(`[ECGViewerContainer ${patient.id}] Adding calibration pulse: ${CALIBRATION_HEAD_SAMPLES} head + ${CALIBRATION_PULSE_SAMPLES} pulse + ${CALIBRATION_TAIL_SAMPLES} tail samples`);
    //   const timeout = setTimeout(() => {
    //     leads.forEach((_, index) => {
    //       if (!hasPulseAdded.current[index]) {
    //         dataBufferRef.current[index] = [...headSamples, ...pulseSamples, ...tailSamples];
    //         hasPulseAdded.current[index] = true;
    //         console.log(`[ECGViewerContainer ${patient.id}] Calibration pulse added to lead ${index}, buffer length: ${dataBufferRef.current[index].length}`);
    //       }
    //     });
    //   }, CALIBRATION_DISPLAY_DELAY_MS);
    //   return () => clearTimeout(timeout);
    // }
  }, [isECGMode, leads, dataBufferRef, patient.id]);

  // ✅ Use centralized config for data buffer management
  // Buffer stores BUFFER_TIME_SECONDS of data to ensure full-screen coverage at 25mm/s
  // Fixed from 8s to 12s to resolve half-screen rendering bug
  useEffect(() => {
    if (!isPaused) {
      const handleDataUpdate = () => {
        dataBufferRef.current.forEach((buffer, index) => {
          if (buffer.length > BUFFER_MAX_SAMPLES) {
            dataBufferRef.current[index] = buffer.slice(-BUFFER_MAX_SAMPLES);
          }
        });
      };
      // Check every 16ms (~60fps) for buffer overflow
      const interval = setInterval(handleDataUpdate, 16);
      return () => clearInterval(interval);
    }
  }, [isPaused, dataBufferRef, patient.id]);

  // Note: Individual canvases handle their own rendering via requestAnimationFrame in ECGWaveformCanvas

  return (
    <div className="fixed inset-0 bg-black z-50 flex flex-col">
      <div className="h-full w-full bg-black text-white flex flex-col">
        <ECGViewerHeader
          patient={patient}
          isECGMode={isECGMode}
          layout={layout}
          selectedLead={selectedLead}
          leads={leads}
          speed={speed}
          gain={gain}
          isPaused={isPaused}
          onClose={onClose}
          onECGModeChange={setIsECGMode}
          onLayoutChange={setLayout}
          onLeadChange={setSelectedLead}
          onSpeedChange={setSpeed}
          onGainChange={setGain}
          onPauseToggle={() => setIsPaused(!isPaused)}
        />
        <ECGDisplayGrid
          patient={patient}
          layout={layout}
          selectedLead={selectedLead}
          leads={leads}
          isECGMode={isECGMode}
          isPaused={isPaused}
          speed={speed}
          gain={gain}
          dataBufferRef={dataBufferRef}
          canvasRefs={canvasRefs}
          getLatestValue={getLatestValue}
        />
      </div>
    </div>
  );
};