"""Generate alerts from vital threshold breaches."""

from typing import Optional
from app.domain.alerts.rules import check_vital_threshold, VITAL_THRESHOLDS
from app.domain.schemas import AlertRecord
from app.common.datetime import now_utc


def generate_vital_alert(
    patient_id: str,
    vital_type: str,
    vital_value: float,
    device_id: Optional[str] = None
) -> Optional[AlertRecord]:
    """
    Generate alert from vital threshold breach.

    Args:
        patient_id: Patient UUID
        vital_type: Type of vital (heartrate, oxygen, temperature, etc.)
        vital_value: Current vital value
        device_id: Optional device ID that generated the vital

    Returns:
        AlertRecord if threshold breached, None if within normal range

    Example:
        >>> alert = generate_vital_alert('patient-123', 'heartrate', 125)
        >>> if alert:
        >>>     print(f"Alert: {alert['message']}")
    """
    # Check if vital breaches threshold
    result = check_vital_threshold(vital_type, vital_value)

    if not result:
        return None  # Within normal range

    severity, threshold_value, message_prefix = result

    # Get vital metadata
    threshold_config = VITAL_THRESHOLDS.get(vital_type, {})
    unit = threshold_config.get('unit', '')

    # Build human-readable message
    vital_name_map = {
        'heartrate': 'Heart Rate',
        'oxygen': 'Oxygen Saturation',
        'temperature': 'Temperature',
        'systolic': 'Systolic BP',
        'diastolic': 'Diastolic BP',
        'respiratory': 'Respiratory Rate'
    }
    vital_name = vital_name_map.get(vital_type, vital_type.title())

    message = f"{message_prefix} {vital_name}: {vital_value}{unit}"

    # Create alert record
    alert: AlertRecord = {
        'id': None,  # Will be generated by database
        'patientId': patient_id,
        'type': 'vital',
        'severity': severity,
        'status': 'active',
        'message': message,
        'vitalType': vital_type,
        'vitalValue': vital_value,
        'thresholdValue': threshold_value,
        'createdBy': device_id or 'system',
        'createdAt': now_utc()
    }

    return alert
