from sqlalchemy import Column, Integer, String, DateTime, ForeignKey
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.sql import func
from enum import Enum

Base = declarative_base()

class BootstrapCodeStatus(str, Enum):
    ACTIVE = "active"
    USED = "used"
    EXPIRED = "expired"

class BootstrapCode(Base):
    """
    Provisioning codes for device bootstrap authentication.
    Generated by hospital IT staff, used once during device provisioning.
    """
    __tablename__ = "bootstrap_codes"

    id = Column(Integer, primary_key=True, index=True)
    code = Column(String(6), unique=True, nullable=False, index=True)
    device_type = Column(String(20), nullable=False)  # 'watch', 'scanner'
    status = Column(String(20), default=BootstrapCodeStatus.ACTIVE, nullable=False)

    # Lifecycle tracking
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    expires_at = Column(DateTime(timezone=True), nullable=False)
    used_at = Column(DateTime(timezone=True))
    used_by_device = Column(String(50))  # Serial number of device that used this code

    # Audit trail
    created_by_staff = Column(Integer, ForeignKey("staff.id"))

    def __repr__(self):
        return f"<BootstrapCode(code='{self.code}', device_type='{self.device_type}', status='{self.status}')>"
