/**
 * CaseSheetService - Patient case sheet (timeline/audit trail) service
 * STRICT CAMELCASE ONLY - No snake_case, no PascalCase for data
 *
 * Purpose: Standardized case sheet operations following BaseMedicalRecordService pattern
 * Note: CaseSheet is unique - it's an audit trail, not a prescribable medical record
 *
 * @module CaseSheetService
 * @since Phase 6
 */

import { BaseMedicalRecordService, MedicalRecordConfig } from './base/BaseMedicalRecordService';
import { caseSheetEntry } from '../types/PatientTypes';
import { PatientTransformer } from '../utils/transformers/PatientTransformer';

/**
 * CaseSheetService - Manages patient case timeline/audit trail
 *
 * Extends BaseMedicalRecordService for consistency with other medical record services.
 * CaseSheet is unique: it's primarily an audit trail of medical actions, not a prescribable record.
 *
 * Key Features:
 * - Inherits ~400 lines of CRUD operations from BaseMedicalRecordService
 * - Provides case entry retrieval with staff resolution
 * - Manual case entry creation (for notes, status changes, etc.)
 * - Timeline/audit trail functionality
 *
 * @example
 * ```typescript
 * // Get case entries with staff data
 * const entries = await CaseSheetService.getCaseEntries('P123');
 *
 * // Add manual case entry
 * await CaseSheetService.addCaseEntry('P123', entryData, 'DOC001');
 * ```
 */
export class CaseSheetService extends BaseMedicalRecordService<caseSheetEntry> {

  // ================================
  // CONFIGURATION
  // ================================

  /**
   * Get configuration for case sheet service
   * @returns Record type configuration
   */
  protected getConfig(): MedicalRecordConfig {
    return {
      recordType: 'case-entries',
      recordTypeSingular: 'case entry',
      recordTypePlural: 'caseEntries'
    };
  }

  // ================================
  // CASE SHEET SPECIFIC METHODS
  // ================================

  /**
   * Get case entries with staff resolution (consolidated endpoint)
   *
   * This method uses a specialized endpoint that includes staff data in the response,
   * eliminating the need for separate API calls. It's optimized for timeline display.
   *
   * @param patientId - Patient ID
   * @returns Promise resolving to array of case entries with staff names resolved
   *
   * @example
   * ```typescript
   * const entries = await CaseSheetService.getCaseEntries('P123');
   * // Returns: [{ id, timestamp, type, description, performedByName, ... }, ...]
   * ```
   */
  static async getCaseEntries(patientId: string): Promise<caseSheetEntry[]> {
    const instance = new CaseSheetService();

    try {
      // Single consolidated call with staff data included
      const response = await instance.fetchFromBackend(
        `/patients/${patientId}/case-entries?includeStaff=true`
      );

      // Extract the caseEntries array from the response
      const caseEntries = response?.caseEntries || [];

      // Extract staff mapping from response (eliminating separate API call)
      const staffData = response?.staff || [];

      // Build staff mapping from embedded staff data
      const staffMapping: { [key: string]: { name: string; role: string } } = {};
      staffData.forEach((staff: any) => {
        const staffId = staff.staffId || staff.id || staff.userId || staff.staff_id;
        if (staffId) {
          const fullName = staff.name || staff.staffName || staff.fullName ||
                          (staff.firstName && staff.lastName ? `${staff.firstName} ${staff.lastName}` : null) ||
                          staff.firstName || staff.lastName || 'Unknown';
          staffMapping[staffId] = {
            name: fullName,
            role: staff.role || staff.staffRole || 'Staff'
          };
        }
      });

      // Transform using unified PatientTransformer with staff mapping for role detection
      const transformedEntries = PatientTransformer.transformCaseTimeline(caseEntries, staffMapping);

      return Array.isArray(transformedEntries) ? transformedEntries : [];
    } catch (error) {
      console.error('Error fetching case entries with staff data:', error);
      return [];
    }
  }

  /**
   * Add manual case entry
   *
   * Note: Most case entries are auto-generated by atomic operations.
   * This method is for manual entries (notes, status changes, etc.)
   *
   * @param patientId - Patient ID
   * @param entryData - Case entry data
   * @param userId - User ID creating the entry
   * @returns Promise resolving to created entry or null
   *
   * @example
   * ```typescript
   * const entry = await CaseSheetService.addCaseEntry('P123', {
   *   entryType: 'statusChange',
   *   description: 'Patient condition improved',
   *   performedBy: 'DOC001'
   * }, 'DOC001');
   * ```
   */
  static async addCaseEntry(
    patientId: string,
    entryData: {
      entryType: string;
      description: string;
      performedBy?: string;
      findings?: string;
      recommendations?: string;
      followUpDate?: string;
      severity?: string;
      category?: string;
    },
    userId: string
  ): Promise<any> {
    const instance = new CaseSheetService();

    try {
      const response = await instance.fetchFromBackend(
        `/patients/${patientId}/case-entries`,
        {
          method: 'POST',
          body: JSON.stringify({
            ...entryData,
            createdBy: userId
            // Let backend handle timestamp creation to avoid datetime format issues
          })
        }
      );

      return response;
    } catch (error) {
      console.error('Error adding case entry:', error);
      return null;
    }
  }

  // ================================
  // INHERITED METHODS FROM BaseMedicalRecordService
  // ================================

  /*
   * The following methods are inherited from BaseMedicalRecordService:
   *
   * - getPatientRecords(patientId): Get all case entries
   * - getActiveRecords(patientId, status): Get filtered case entries
   * - addRecord(patientId, data, userId): Add case entry with atomic operation
   * - updateRecordStatus(recordId, status, userId): Update case entry status
   * - getRecordTypes(): Get case entry type enumerators
   * - getRecordHistory(patientId, recordId?): Get case entry history
   * - getRecordTimeline(patientId, hoursBack?, timeField?): Get case entry timeline
   * - getRecordsByStatus(patientId, status): Get case entries by status
   *
   * These methods provide ~400 lines of CRUD operations without code duplication.
   */

  // ================================
  // PAYLOAD TRANSFORMATION
  // ================================

  /**
   * Transform add payload for case entry creation
   *
   * Maps frontend field names to backend API requirements.
   * Override from BaseMedicalRecordService.
   *
   * @param entryData - Raw entry data from form
   * @param userId - User ID
   * @returns Transformed payload for API
   */
  protected transformAddPayload(entryData: any, userId: string): any {
    return {
      entryType: entryData.entryType || entryData.type,
      description: entryData.description,
      performedBy: entryData.performedBy || userId,
      findings: entryData.findings,
      recommendations: entryData.recommendations,
      followUpDate: entryData.followUpDate,
      severity: entryData.severity,
      category: entryData.category,
      // Backend handles timestamp creation
    };
  }
}
