"""
AlertPipeline - Single source of truth for alert generation and processing.

Replaces multiple alert generation logic scattered across:
- app/services/vital_alert_service.py (DEPRECATED - will be deleted)
- app/services/alert_manager_service.py
- app/services/mqtt_service.py (inline alert generation)

Usage:
    from app.domain.alerts import AlertPipeline

    pipeline = AlertPipeline(pool=db_pool)
    alert = await pipeline.generate_vital_alert(patient_id, vital_type, value)
    await pipeline.process_alert(alert)
"""

from typing import Optional, Dict, Any
from datetime import datetime
import logging
import asyncpg

from app.domain.schemas import (
    AlertRecord, AlertType, AlertSeverity, AlertStatus,
    VitalsRecord, VITAL_THRESHOLDS
)
from app.common import to_utc_now
from .deduplicator import AlertDeduplicator

logger = logging.getLogger(__name__)


class AlertPipeline:
    """
    Centralizes alert generation, validation, and processing.

    Responsibilities:
    1. Generate alerts from vital threshold breaches
    2. Generate arrhythmia detection alerts
    3. Generate device malfunction alerts
    4. Apply deduplication logic
    5. Insert alerts into database
    6. Trigger WebSocket broadcasts
    """

    def __init__(self, pool: asyncpg.Pool):
        """
        Initialize alert pipeline.

        Args:
            pool: Database connection pool
        """
        self.pool = pool
        self.deduplicator = AlertDeduplicator(pool)
        self.thresholds = VITAL_THRESHOLDS

    async def generate_vital_alert(
        self,
        patient_id: str,
        vital_type: str,
        vital_value: float,
        device_id: Optional[str] = None
    ) -> Optional[AlertRecord]:
        """
        Generate alert from vital threshold breach.

        Args:
            patient_id: Patient UUID
            vital_type: Type of vital (heartrate, oxygen, temperature, etc.)
            vital_value: Current vital value
            device_id: Optional device ID that generated the vital

        Returns:
            AlertRecord if alert should be created, None if deduplicated
        """
        # Check if vital type has thresholds
        if vital_type not in self.thresholds:
            logger.warning(f"No thresholds defined for vital type: {vital_type}")
            return None

        threshold = self.thresholds[vital_type]

        # Determine severity and threshold value breached
        severity: Optional[AlertSeverity] = None
        threshold_value: Optional[float] = None
        message_prefix = ""

        if vital_value <= threshold.get('criticalLow', float('-inf')):
            severity = 'critical'
            threshold_value = threshold['criticalLow']
            message_prefix = "Critical Low"
        elif vital_value >= threshold.get('criticalHigh', float('inf')):
            severity = 'critical'
            threshold_value = threshold['criticalHigh']
            message_prefix = "Critical High"
        elif vital_value <= threshold.get('warningLow', float('-inf')):
            severity = 'high'
            threshold_value = threshold['warningLow']
            message_prefix = "Low"
        elif vital_value >= threshold.get('warningHigh', float('inf')):
            severity = 'high'
            threshold_value = threshold['warningHigh']
            message_prefix = "High"
        else:
            # Value is within normal range
            return None

        # Check deduplication
        is_duplicate = await self.deduplicator.is_duplicate_alert(
            patient_id=patient_id,
            vital_type=vital_type,
            window_minutes=5
        )

        if is_duplicate:
            logger.info(f"Deduplicated alert for patient {patient_id}, vital {vital_type}")
            return None

        # Build human-readable message
        vital_name_map = {
            'heartrate': 'Heart Rate',
            'oxygen': 'Oxygen Saturation',
            'temperature': 'Temperature',
            'systolic': 'Systolic BP',
            'diastolic': 'Diastolic BP',
            'respiratory': 'Respiratory Rate'
        }
        vital_name = vital_name_map.get(vital_type, vital_type.title())
        unit = threshold.get('unit', '')

        message = f"{message_prefix} {vital_name}: {vital_value}{unit}"

        # Create alert record
        alert: AlertRecord = {
            'id': None,  # Will be generated by database
            'patientId': patient_id,
            'type': 'vital',
            'severity': severity,
            'status': 'active',
            'message': message,
            'vitalType': vital_type,
            'vitalValue': vital_value,
            'thresholdValue': threshold_value,
            'createdBy': device_id or 'system',
            'createdAt': to_utc_now()
        }

        return alert

    async def generate_arrhythmia_alert(
        self,
        patient_id: str,
        arrhythmia_type: str,
        confidence: float,
        ecg_metrics: Dict[str, Any],
        device_id: Optional[str] = None
    ) -> Optional[AlertRecord]:
        """
        Generate alert from arrhythmia detection.

        Args:
            patient_id: Patient UUID
            arrhythmia_type: Type of arrhythmia detected
            confidence: Detection confidence (0.0-1.0)
            ecg_metrics: ECG metrics that triggered detection
            device_id: Device ID that detected arrhythmia

        Returns:
            AlertRecord if alert should be created
        """
        # Determine severity based on arrhythmia type and confidence
        severity: AlertSeverity = 'medium'
        if arrhythmia_type in ['ventricular_fibrillation', 'ventricular_tachycardia']:
            severity = 'critical'
        elif arrhythmia_type in ['atrial_fibrillation', 'supraventricular_tachycardia']:
            severity = 'high'
        elif confidence >= 0.9:
            severity = 'high'

        # Build message
        arrhythmia_name_map = {
            'ventricular_fibrillation': 'Ventricular Fibrillation',
            'ventricular_tachycardia': 'Ventricular Tachycardia',
            'atrial_fibrillation': 'Atrial Fibrillation',
            'supraventricular_tachycardia': 'SVT',
            'bradycardia': 'Bradycardia',
            'tachycardia': 'Tachycardia'
        }
        arrhythmia_name = arrhythmia_name_map.get(arrhythmia_type, arrhythmia_type.replace('_', ' ').title())
        message = f"Arrhythmia Detected: {arrhythmia_name} (confidence: {confidence:.0%})"

        # Create alert record
        alert: AlertRecord = {
            'id': None,
            'patientId': patient_id,
            'type': 'arrhythmia',
            'severity': severity,
            'status': 'active',
            'message': message,
            'createdBy': device_id or 'system',
            'createdAt': to_utc_now()
        }

        return alert

    async def generate_device_alert(
        self,
        patient_id: str,
        device_id: str,
        issue: str,
        severity: AlertSeverity = 'medium'
    ) -> AlertRecord:
        """
        Generate alert for device malfunction or connectivity issue.

        Args:
            patient_id: Patient UUID
            device_id: Device ID with issue
            issue: Description of the issue
            severity: Alert severity

        Returns:
            AlertRecord
        """
        alert: AlertRecord = {
            'id': None,
            'patientId': patient_id,
            'type': 'device',
            'severity': severity,
            'status': 'active',
            'message': f"Device {device_id}: {issue}",
            'createdBy': 'system',
            'createdAt': to_utc_now()
        }

        return alert

    async def process_alert(self, alert: AlertRecord) -> str:
        """
        Process alert: insert into database and return alert ID.

        Args:
            alert: AlertRecord to process

        Returns:
            Alert UUID from database

        Raises:
            Exception: If database insertion fails
        """
        try:
            async with self.pool.acquire() as conn:
                # Insert alert into patient_alerts table
                query = """
                    INSERT INTO patient_alerts (
                        "patientId", type, severity, status, message,
                        "vitalType", "vitalValue", "thresholdValue",
                        "createdBy", "createdAt"
                    )
                    VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
                    RETURNING id
                """

                alert_id = await conn.fetchval(
                    query,
                    alert['patientId'],
                    alert['type'],
                    alert['severity'],
                    alert['status'],
                    alert['message'],
                    alert.get('vitalType'),
                    alert.get('vitalValue'),
                    alert.get('thresholdValue'),
                    alert.get('createdBy', 'system'),
                    alert['createdAt']
                )

                logger.info(f"Created alert {alert_id} for patient {alert['patientId']}")
                return str(alert_id)

        except Exception as e:
            logger.error(f"Failed to process alert: {e}")
            raise

    async def acknowledge_alert(
        self,
        alert_id: str,
        acknowledged_by: str
    ) -> bool:
        """
        Acknowledge an alert.

        Args:
            alert_id: Alert UUID
            acknowledged_by: Staff ID who acknowledged

        Returns:
            True if successful
        """
        try:
            async with self.pool.acquire() as conn:
                query = """
                    UPDATE patient_alerts
                    SET status = 'acknowledged',
                        "acknowledgedBy" = $2,
                        "acknowledgedAt" = $3
                    WHERE id = $1
                    RETURNING id
                """

                result = await conn.fetchval(
                    query,
                    alert_id,
                    acknowledged_by,
                    to_utc_now()
                )

                if result:
                    logger.info(f"Alert {alert_id} acknowledged by {acknowledged_by}")
                    return True
                else:
                    logger.warning(f"Alert {alert_id} not found for acknowledgment")
                    return False

        except Exception as e:
            logger.error(f"Failed to acknowledge alert {alert_id}: {e}")
            return False

    async def resolve_alert(
        self,
        alert_id: str,
        resolved_by: str,
        resolution_reason: Optional[str] = None
    ) -> bool:
        """
        Resolve an alert.

        Args:
            alert_id: Alert UUID
            resolved_by: Staff ID who resolved (or 'system')
            resolution_reason: Optional reason for resolution

        Returns:
            True if successful
        """
        try:
            async with self.pool.acquire() as conn:
                query = """
                    UPDATE patient_alerts
                    SET status = 'resolved',
                        "resolvedBy" = $2,
                        "resolvedAt" = $3
                    WHERE id = $1
                    RETURNING id
                """

                result = await conn.fetchval(
                    query,
                    alert_id,
                    resolved_by,
                    to_utc_now()
                )

                if result:
                    logger.info(f"Alert {alert_id} resolved by {resolved_by}")
                    return True
                else:
                    logger.warning(f"Alert {alert_id} not found for resolution")
                    return False

        except Exception as e:
            logger.error(f"Failed to resolve alert {alert_id}: {e}")
            return False
